% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{HW04}
\author{Chongdan Pan}
\date{2022/2/4}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={HW04},
  pdfauthor={Chongdan Pan},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{problem-1}{%
\section{Problem 1}\label{problem-1}}

\hypertarget{a}{%
\subsubsection{(a)}\label{a}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../Rus2000\_daily\_Feb3\_2017{-}Feb3\_2022.csv"}\NormalTok{, }\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{ret }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Adj.Close[}\DecValTok{2}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(df)] }\SpecialCharTok{/}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Adj.Close[}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(df)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}} \DecValTok{1}
\FunctionTok{hist}\NormalTok{(ret, }\AttributeTok{breaks=}\DecValTok{50}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{HW04_files/figure-latex/unnamed-chunk-1-1} \end{center}

The return seems to be symmetric to the 0, and it has a high kurtosis
since there a lot of data in near 0, therefore it distribution may have
a heavy tail although we don't have a lot of samples with high absolute
value.

\hypertarget{b}{%
\subsubsection{(b)}\label{b}}

\begin{longtable}[]{@{}lllll@{}}
\toprule
median & mean & variance & skewness & kurtosis \\
\midrule
\endhead
0.0008414 & 0.0004222 & 0.0002433763 & -0.9844468 & 13.37257 \\
\bottomrule
\end{longtable}

The mean, median, and skewness are close to zero, so the data is
symmetric to 0. The kurtosis is very high, implying that the data may
have a heavy tail.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(ret), }\AttributeTok{main=}\StringTok{"Kernel Density Estimate"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{HW04_files/figure-latex/unnamed-chunk-2-1} \end{center}

The estimate result is quite good since it's smooth and similar to the
original histogram. In addition, it's clearly showing the high kurotsis
and low skewness.

\hypertarget{c}{%
\subsubsection{(c)}\label{c}}

\begin{Shaded}
\begin{Highlighting}[]
\SpecialCharTok{{-}}\FloatTok{1e6} \SpecialCharTok{*} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.005}\NormalTok{, }\FunctionTok{mean}\NormalTok{(ret), }\FunctionTok{sd}\NormalTok{(ret))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 39762.09
\end{verbatim}

Therefore, the VaR from normal distribution estimation is 39762.09
dollars

\hypertarget{d}{%
\subsubsection{(d)}\label{d}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(evir)}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{loss }\OtherTok{=} \SpecialCharTok{{-}}\NormalTok{ret}
\NormalTok{eecdf }\OtherTok{=} \FunctionTok{ecdf}\NormalTok{(loss)}
\FunctionTok{plot}\NormalTok{(eecdf, }\AttributeTok{main=}\StringTok{"ECDF of Loss"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Claims"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"ECDF"}\NormalTok{)}
\NormalTok{uv }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from =} \FloatTok{0.025}\NormalTok{,}\AttributeTok{to =} \FloatTok{0.1}\NormalTok{, }\AttributeTok{by =}\NormalTok{ .}\DecValTok{001}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(uv,}\FunctionTok{eecdf}\NormalTok{(uv), }\AttributeTok{main=}\StringTok{"ECDF of Loss Tail"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Claims"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"ECDF"}\NormalTok{)}
\FunctionTok{shape}\NormalTok{(loss, }\AttributeTok{models=}\DecValTok{30}\NormalTok{, }\AttributeTok{start=}\DecValTok{300}\NormalTok{, }\AttributeTok{end=}\DecValTok{20}\NormalTok{, }\AttributeTok{ci=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{reverse =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{auto.scale=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{mu }\OtherTok{=} \FloatTok{0.015}
\NormalTok{gpd\_out }\OtherTok{=} \FunctionTok{gpd}\NormalTok{(loss, }\AttributeTok{threshold =}\NormalTok{ mu)}
\NormalTok{gpd\_out}\SpecialCharTok{$}\NormalTok{par.ests}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         xi       beta 
## 0.29026972 0.00885722
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tailplot}\NormalTok{(gpd\_out)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{HW04_files/figure-latex/unnamed-chunk-4-1} \end{center}

It turns out when I set the threshold to be 0.015, the result from tail
plot is linear, and the shape parameter is around 0.29

\hypertarget{e}{%
\subsubsection{(e)}\label{e}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qt }\OtherTok{=} \DecValTok{1}\FloatTok{{-}.005}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{eecdf}\NormalTok{(mu))}
\NormalTok{xi }\OtherTok{=}\NormalTok{ gpd\_out}\SpecialCharTok{$}\NormalTok{par.ests[}\DecValTok{1}\NormalTok{]}
\NormalTok{scale }\OtherTok{=}\NormalTok{ gpd\_out}\SpecialCharTok{$}\NormalTok{par.ests[}\DecValTok{2}\NormalTok{]}
\NormalTok{VaR }\OtherTok{=} \FunctionTok{qgpd}\NormalTok{(qt, xi, mu, scale)}
\FloatTok{1e6} \SpecialCharTok{*}\NormalTok{ VaR}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    beta 
## 57985.9
\end{verbatim}

The VaR result is 57985.9 dollars, which is much larger than the result
from normal distribution. Therefore, it's inappropriate to estimate the
tail through empirical distribution when \(q\) is small.

\hypertarget{f}{%
\subsubsection{(f)}\label{f}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{quant}\NormalTok{(loss, }\AttributeTok{p =} \FloatTok{0.995}\NormalTok{, }\AttributeTok{models =} \DecValTok{20}\NormalTok{, }\AttributeTok{start =} \DecValTok{600}\NormalTok{, }\AttributeTok{end =} \DecValTok{40}\NormalTok{, }\AttributeTok{reverse =}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ci =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{auto.scale =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{labels =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{HW04_files/figure-latex/unnamed-chunk-6-1} \end{center}

It turns out that the VaR is quite stable in the range from 0.003 to
0.018, and setting threshold to be 0.015 can work well for tail
estimation.

\hypertarget{g}{%
\subsubsection{(g)}\label{g}}

\begin{itemize}
\tightlist
\item
  For ES in part(c)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{1e6} \SpecialCharTok{*}\NormalTok{ (}\FunctionTok{mean}\NormalTok{(ret) }\SpecialCharTok{+} \FunctionTok{sd}\NormalTok{(ret) }\SpecialCharTok{*} \FunctionTok{dnorm}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.005}\NormalTok{)) }\SpecialCharTok{/} \FloatTok{0.005}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 45538.1
\end{verbatim}

The expected shortfall is 45538.1 dollars

\begin{itemize}
\tightlist
\item
  For ES in part(e)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qt }\OtherTok{=} \DecValTok{1}\FloatTok{{-}.005}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{eecdf}\NormalTok{(mu))}
\NormalTok{xi }\OtherTok{=}\NormalTok{ gpd\_out}\SpecialCharTok{$}\NormalTok{par.ests[}\DecValTok{1}\NormalTok{]}
\NormalTok{scale }\OtherTok{=}\NormalTok{ gpd\_out}\SpecialCharTok{$}\NormalTok{par.ests[}\DecValTok{2}\NormalTok{]}
\FloatTok{1e6} \SpecialCharTok{*}\NormalTok{ (VaR }\SpecialCharTok{+}\NormalTok{ (scale }\SpecialCharTok{+}\NormalTok{ xi }\SpecialCharTok{*}\NormalTok{ (VaR }\SpecialCharTok{{-}}\NormalTok{ mu)) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ xi))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     beta 
## 88046.23
\end{verbatim}

The expected shortfall is 88046.23 dollars

\hypertarget{section}{%
\section{2}\label{section}}

\hypertarget{a-1}{%
\subsubsection{(a)}\label{a-1}}

\[
COV[X,Y] = COV[X, X^2] = E[(X-E[X])(X^2 - E[X^2])]=E[X^3]=0
\]

The covariance of \(X\) and \(Y\) is 0, so they're not correlated.
However, since \(Y=X^2\), then they're not independent.

\hypertarget{b-1}{%
\subsubsection{(b)}\label{b-1}}

Based on the definition, we have \[
\hat\rho_S=\frac{12}{n(n^2-1)}[\sum_{i=0}^{\lfloor n/2\rfloor}(2*i + 1-\frac{n+1}{2})(n+1-n-1)-(\lfloor n/2\rfloor-\frac{n+1}{2})(1-\frac{n+1}{2})]
\\\hat\rho_S=0
\]

\hypertarget{c-1}{%
\subsubsection{(c)}\label{c-1}}

\[\text{Let}\quad w=\begin{bmatrix}x\\y\\z\end{bmatrix}
\\\text{Then}\quad Var(w^TY)=w^TCov(Y)w=x^2+y^2+z^2+1.8(xy+yz+axz)
\\\text{Assume}\quad a=0\quad\text{and}\quad x=z=1,y=-1.8
\\\text{Then}\quad Var(w^TY)=-1.24
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{w }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{1.8}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{x }\OtherTok{=}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\DecValTok{0}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\DecValTok{0}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{nrow=}\DecValTok{3}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{3}\NormalTok{)}
\FunctionTok{t}\NormalTok{(w)}\SpecialCharTok{\%*\%}\NormalTok{x}\SpecialCharTok{\%*\%}\NormalTok{w}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1]
## [1,] -1.24
\end{verbatim}

Since the variance should be always larger than 0, then \(a\) can't be 0

\hypertarget{d-1}{%
\subsubsection{(d)}\label{d-1}}

Since the matrix is covariance, then all its eigenvalues must greater
than 0. To calculate the eigenvalues, we have

\[
\begin{bmatrix}1-\lambda&0.9&a\\0.9&1-\lambda&0.9\\a&0.9&1-\lambda\end{bmatrix}=0
\\\text{Hence,it's determinant is}\quad(1-\lambda-a)[\lambda^2-(2+a)\lambda+a-0.62]=0
\\\text{Then we have three eigenvalues}\quad \lambda_1=1-a,\lambda_2=\frac{a+2+\sqrt{a^2+6.48}}{2},\lambda_3=\frac{a+2-\sqrt{a^2+6.48}}{2}
\\\text{Since all eigenvalues must be greater or equal to 0, we have }0.62\leq a\leq 1 
\]

Therefore, the lower limit on \(a\) is 0.62

\end{document}
